### PR TITLE
📄 Commit Guide: Added instructions

### PR DESCRIPTION
**Pull request by FoxMoss**
Just added some dry instructions on how to commit commits with the commit style. It goes over creating a branch commiting and creating a PR, though it is by no means a step by step guide (missing pushing and adding which is assumed git knoledge).

Mostly for myself but it'll be helpfull to new members, considering I fucked it up once while trying to add this.

I DIDNT FUCK ANYTHING UP I SWEAR TO GOD

### CODE REVIEW

**Comment by FoxMoss** [comment]
@jessiejs

**Comment by jessiejs** [comment]
A much easier way to write commits is to do `git commit -a` with no message.
It will open vim and let you write the commit without weird flags.

**Comment by jessiejs** [comment]
@FoxMoss

**Comment by jessiejs** [comment]
@FoxMoss merge commit + see https://github.com/swarm-team/style/pull/3#issuecomment-1550671882

**Comment by jessiejs** [comment]
@FoxMoss Closing this

**Pull request closed without merging**
